In [1]:
# pip install tensorflow==2.0

In [2]:
import tensorflow as tf
print(tf.__version__)

2.1.0

# Importing Libraries

In [3]:
import tensorflow as tf
import numpy as np 
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import MinMaxScaler 
# import sys
# np.set_printoptions(threshold=sys.maxsize)

# Data

In [4]:
data = pd.read_excel("todoData.xlsx", date_parser=True)
data.head()

,Date,bread,egg,waffles,butter,milk,yogurt,burrito,cereal,cheese,...,strawberry,peach,coriander,mint,tomato,onion,potatoes,garlic,ginger,pepper
0,2018-01-01,1,1,1,1,1,1,0,1,0,...,0,1,1,0,1,1,1,1,1,0
1,2018-01-02,1,0,0,0,1,1,0,0,1,...,0,0,1,0,0,0,0,0,0,0
2,2018-01-03,0,0,0,0,1,1,0,0,0,...,0,0,0,0,1,0,0,0,0,0
3,2018-01-04,1,1,0,0,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,0
4,2018-01-05,1,1,0,0,1,1,0,1,0,...,1,1,1,0,1,0,0,1,1,1

In [5]:
# Training Data

In [6]:
#train data before 2019-06-30

training_data = data[data["Date"]< "2019-06-30"].copy()
training_data

,Date,bread,egg,waffles,butter,milk,yogurt,burrito,cereal,cheese,...,strawberry,peach,coriander,mint,tomato,onion,potatoes,garlic,ginger,pepper
0,2018-01-01,1,1,1,1,1,1,0,1,0,...,0,1,1,0,1,1,1,1,1,0
1,2018-01-02,1,0,0,0,1,1,0,0,1,...,0,0,1,0,0,0,0,0,0,0
2,2018-01-03,0,0,0,0,1,1,0,0,0,...,0,0,0,0,1,0,0,0,0,0
3,2018-01-04,1,1,0,0,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,0
4,2018-01-05,1,1,0,0,1,1,0,1,0,...,1,1,1,0,1,0,0,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,2019-06-25,1,1,1,1,1,0,0,0,0,...,0,1,1,0,1,1,0,1,1,0
541,2019-06-26,1,0,0,1,1,1,0,0,0,...,0,0,1,0,0,0,0,0,0,0
542,2019-06-27,0,0,0,0,1,1,0,0,0,...,0,0,0,0,1,0,0,0,0,0
543,2019-06-28,1,1,0,0,1,0,0,1,1,...,0,0,1,1,1,0,0,0,0,0
544,2019-06-29,1,1,0,0,1,1,0,1,0,...,1,1,1,0,1,0,0,1,1,1

# Testing Data

In [7]:
#test data after 2019-06-29

testing_data = data[data["Date"]>"2019-06-29"].copy()
testing_data

,Date,bread,egg,waffles,butter,milk,yogurt,burrito,cereal,cheese,...,strawberry,peach,coriander,mint,tomato,onion,potatoes,garlic,ginger,pepper
545,2019-06-30,0,0,0,0,1,1,0,0,0,...,0,1,0,0,1,0,0,0,0,0
546,2019-07-01,1,0,0,1,1,1,0,0,0,...,0,0,1,0,1,0,0,0,0,0
547,2019-07-02,1,1,0,1,1,0,0,0,0,...,0,0,1,1,0,0,0,0,0,0
548,2019-07-03,0,1,0,0,1,1,0,1,0,...,0,0,0,0,1,0,0,1,1,0
549,2019-07-04,1,0,0,0,0,1,0,0,0,...,1,1,1,0,1,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
725,2019-12-27,1,0,0,1,1,1,0,0,0,...,0,1,0,0,1,0,0,0,0,0
726,2019-12-28,1,0,0,0,1,1,0,0,0,...,0,1,1,0,1,0,0,0,0,0
727,2019-12-29,1,1,0,0,1,0,0,0,0,...,0,0,1,1,0,0,0,0,0,0
728,2019-12-30,0,0,0,0,1,1,0,0,1,...,0,0,0,0,1,0,0,1,1,0
729,2019-12-31,1,0,0,0,0,1,0,1,0,...,1,0,1,0,1,1,0,0,0,1

# Removing Date Columns From Train Data

In [8]:
#removing unnecessary columns

train_data = training_data.drop(["Date"], axis=1)
train_data

,bread,egg,waffles,butter,milk,yogurt,burrito,cereal,cheese,beef,...,strawberry,peach,coriander,mint,tomato,onion,potatoes,garlic,ginger,pepper
0,1,1,1,1,1,1,0,1,0,0,...,0,1,1,0,1,1,1,1,1,0
1,1,0,0,0,1,1,0,0,1,0,...,0,0,1,0,0,0,0,0,0,0
2,0,0,0,0,1,1,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
3,1,1,0,0,1,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,0
4,1,1,0,0,1,1,0,1,0,0,...,1,1,1,0,1,0,0,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1,1,1,1,1,0,0,0,0,0,...,0,1,1,0,1,1,0,1,1,0
541,1,0,0,1,1,1,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
542,0,0,0,0,1,1,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
543,1,1,0,0,1,0,0,1,1,0,...,0,0,1,1,1,0,0,0,0,0
544,1,1,0,0,1,1,0,1,0,0,...,1,1,1,0,1,0,0,1,1,1

# Normalizing Values

In [9]:
#normalizing values 

scaler = MinMaxScaler()
train_data = scaler.fit_transform(train_data)
train_data

array([[1., 1., 1., ..., 1., 1., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 1., 0., ..., 0., 0., 0.],
       [1., 1., 0., ..., 1., 1., 1.]])

# Preparing Training Data

In [10]:
x_train = []
y_train = []

In [11]:
# training on 3 days then predciting 4th value

for i in range (3, train_data.shape[0]):
    x_train.append(train_data[i-3:i])
    y_train.append(train_data[i])
    
# train_data[i]

In [12]:
x_train , y_train = np.array(x_train), np.array(y_train)

In [13]:
x_train.shape

(542, 3, 29)

In [14]:
y_train.shape

(542, 29)

# Building Model

In [15]:
# building LSTM network

from tensorflow.keras import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout

regressor = Sequential()

regressor.add(LSTM(units = 100, activation = "relu", return_sequences = True, input_shape= (x_train.shape[1],29)))
regressor.add(Dropout(0.2))

regressor.add(LSTM(units = 100, activation = "relu", return_sequences = True))
regressor.add(Dropout(0.2))

regressor.add(LSTM(units = 120, activation = "relu"))
regressor.add(Dropout(0.2))

# regressor.add(LSTM(units = 120, activation = "relu"))
# regressor.add(Dropout(0.2))
regressor.add(Dense(29, activation='sigmoid'))

In [16]:
regressor.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
lstm (LSTM)                  (None, 3, 100)            52000
_________________________________________________________________
dropout (Dropout)            (None, 3, 100)            0
_________________________________________________________________
lstm_1 (LSTM)                (None, 3, 100)            80400
_________________________________________________________________
dropout_1 (Dropout)          (None, 3, 100)            0
_________________________________________________________________
lstm_2 (LSTM)                (None, 120)               106080
_________________________________________________________________
dropout_2 (Dropout)          (None, 120)               0
_________________________________________________________________
dense (Dense)                (None, 29)                3509
=================================================================
Total params: 241,989
Trainable params: 241,989
Non-trainable params: 0
_________________________________________________________________

In [17]:
#compiling the regressor model

regressor.compile(optimizer="adam", loss="binary_crossentropy", metrics=["acc"])

In [18]:
#training the the model

regressor.fit(x_train, y_train, epochs=150, batch_size=12)

Train on 542 samples
Epoch 1/150
542/542 [==============================] - 6s 11ms/sample - loss: 0.6008 - acc: 0.7621
Epoch 2/150
542/542 [==============================] - 1s 1ms/sample - loss: 0.5034 - acc: 0.7712
Epoch 3/150
542/542 [==============================] - 1s 1ms/sample - loss: 0.4942 - acc: 0.7739
Epoch 4/150
542/542 [==============================] - 1s 1ms/sample - loss: 0.4866 - acc: 0.7775
Epoch 5/150
542/542 [==============================] - 1s 1ms/sample - loss: 0.4699 - acc: 0.7862
Epoch 6/150
542/542 [==============================] - 1s 1ms/sample - loss: 0.4270 - acc: 0.8103
Epoch 7/150
542/542 [==============================] - 1s 2ms/sample - loss: 0.3933 - acc: 0.8272
Epoch 8/150
542/542 [==============================] - 1s 989us/sample - loss: 0.3652 - acc: 0.8436
Epoch 9/150
542/542 [==============================] - 1s 1ms/sample - loss: 0.3392 - acc: 0.8570
Epoch 10/150
542/542 [==============================] - 1s 2ms/sample - loss: 0.3239 - acc: 0.8648
Epoch 11/150
542/542 [==============================] - 1s 2ms/sample - loss: 0.3088 - acc: 0.8707
Epoch 12/150
542/542 [==============================] - 1s 1ms/sample - loss: 0.2995 - acc: 0.8757
Epoch 13/150
542/542 [==============================] - 1s 1ms/sample - loss: 0.2936 - acc: 0.8759
Epoch 14/150
542/542 [==============================] - 0s 894us/sample - loss: 0.2826 - acc: 0.8816
Epoch 15/150
542/542 [==============================] - 0s 823us/sample - loss: 0.2761 - acc: 0.8838
Epoch 16/150
542/542 [==============================] - 0s 839us/sample - loss: 0.2681 - acc: 0.8896
Epoch 17/150
542/542 [==============================] - 0s 865us/sample - loss: 0.2629 - acc: 0.8943
Epoch 18/150
542/542 [==============================] - 0s 849us/sample - loss: 0.2548 - acc: 0.8963
Epoch 19/150
542/542 [==============================] - 0s 833us/sample - loss: 0.2444 - acc: 0.9001
Epoch 20/150
542/542 [==============================] - 0s 858us/sample - loss: 0.2452 - acc: 0.8999
Epoch 21/150
542/542 [==============================] - 0s 863us/sample - loss: 0.2391 - acc: 0.9025
Epoch 22/150
542/542 [==============================] - 0s 832us/sample - loss: 0.2348 - acc: 0.9054
Epoch 23/150
542/542 [==============================] - 0s 868us/sample - loss: 0.2296 - acc: 0.9048
Epoch 24/150
542/542 [==============================] - 0s 840us/sample - loss: 0.2255 - acc: 0.9073
Epoch 25/150
542/542 [==============================] - 0s 879us/sample - loss: 0.2259 - acc: 0.9051
Epoch 26/150
542/542 [==============================] - 0s 844us/sample - loss: 0.2194 - acc: 0.9114
Epoch 27/150
542/542 [==============================] - 0s 855us/sample - loss: 0.2128 - acc: 0.9118
Epoch 28/150
542/542 [==============================] - 0s 827us/sample - loss: 0.2155 - acc: 0.9118
Epoch 29/150
542/542 [==============================] - 0s 861us/sample - loss: 0.2100 - acc: 0.9142
Epoch 30/150
542/542 [==============================] - 0s 843us/sample - loss: 0.2056 - acc: 0.9170
Epoch 31/150
542/542 [==============================] - 0s 864us/sample - loss: 0.2027 - acc: 0.9182
Epoch 32/150
542/542 [==============================] - 0s 834us/sample - loss: 0.2080 - acc: 0.9152
Epoch 33/150
542/542 [==============================] - 0s 856us/sample - loss: 0.1977 - acc: 0.9210
Epoch 34/150
542/542 [==============================] - 0s 840us/sample - loss: 0.1912 - acc: 0.9219
Epoch 35/150
542/542 [==============================] - 0s 849us/sample - loss: 0.1914 - acc: 0.9202
Epoch 36/150
542/542 [==============================] - 0s 866us/sample - loss: 0.1929 - acc: 0.9214
Epoch 37/150
542/542 [==============================] - 0s 832us/sample - loss: 0.1890 - acc: 0.9209
Epoch 38/150
542/542 [==============================] - 0s 843us/sample - loss: 0.1841 - acc: 0.9231
Epoch 39/150
542/542 [==============================] - 0s 850us/sample - loss: 0.1835 - acc: 0.9227
Epoch 40/150
542/542 [==============================] - 0s 874us/sample - loss: 0.1781 - acc: 0.9256
Epoch 41/150
542/542 [==============================] - 0s 833us/sample - loss: 0.1830 - acc: 0.9236
Epoch 42/150
542/542 [==============================] - 0s 890us/sample - loss: 0.1769 - acc: 0.9256
Epoch 43/150
542/542 [==============================] - 0s 834us/sample - loss: 0.1748 - acc: 0.9275
Epoch 44/150
542/542 [==============================] - 0s 838us/sample - loss: 0.1694 - acc: 0.9270
Epoch 45/150
542/542 [==============================] - 0s 868us/sample - loss: 0.1672 - acc: 0.9304
Epoch 46/150
542/542 [==============================] - 0s 857us/sample - loss: 0.1705 - acc: 0.9284
Epoch 47/150
542/542 [==============================] - 0s 865us/sample - loss: 0.1663 - acc: 0.9274
Epoch 48/150
542/542 [==============================] - 0s 851us/sample - loss: 0.1625 - acc: 0.9313
Epoch 49/150
542/542 [==============================] - 0s 879us/sample - loss: 0.1615 - acc: 0.9309
Epoch 50/150
542/542 [==============================] - 0s 845us/sample - loss: 0.1575 - acc: 0.9322
Epoch 51/150
542/542 [==============================] - 0s 862us/sample - loss: 0.1561 - acc: 0.9318
Epoch 52/150
542/542 [==============================] - 0s 867us/sample - loss: 0.1582 - acc: 0.9319
Epoch 53/150
542/542 [==============================] - 0s 845us/sample - loss: 0.1525 - acc: 0.9322
Epoch 54/150
542/542 [==============================] - 0s 875us/sample - loss: 0.1540 - acc: 0.9321
Epoch 55/150
542/542 [==============================] - 0s 848us/sample - loss: 0.1482 - acc: 0.9336
Epoch 56/150
542/542 [==============================] - 0s 839us/sample - loss: 0.1491 - acc: 0.9331
Epoch 57/150
542/542 [==============================] - 0s 836us/sample - loss: 0.1512 - acc: 0.9340
Epoch 58/150
542/542 [==============================] - 0s 867us/sample - loss: 0.1469 - acc: 0.9361
Epoch 59/150
542/542 [==============================] - 0s 865us/sample - loss: 0.1414 - acc: 0.9384
Epoch 60/150
542/542 [==============================] - 1s 991us/sample - loss: 0.1512 - acc: 0.9342
Epoch 61/150
542/542 [==============================] - 0s 877us/sample - loss: 0.1378 - acc: 0.9379
Epoch 62/150
542/542 [==============================] - 0s 864us/sample - loss: 0.1378 - acc: 0.9405
Epoch 63/150
542/542 [==============================] - 0s 857us/sample - loss: 0.1359 - acc: 0.9387
Epoch 64/150
542/542 [==============================] - 0s 851us/sample - loss: 0.1312 - acc: 0.9413
Epoch 65/150
542/542 [==============================] - 0s 845us/sample - loss: 0.1320 - acc: 0.9403
Epoch 66/150
542/542 [==============================] - 0s 883us/sample - loss: 0.1264 - acc: 0.9434
Epoch 67/150
542/542 [==============================] - 0s 916us/sample - loss: 0.1308 - acc: 0.9412
Epoch 68/150
542/542 [==============================] - 1s 1ms/sample - loss: 0.1274 - acc: 0.9432
Epoch 69/150
542/542 [==============================] - 0s 870us/sample - loss: 0.1297 - acc: 0.9408
Epoch 70/150
542/542 [==============================] - 0s 866us/sample - loss: 0.1230 - acc: 0.9462
Epoch 71/150
542/542 [==============================] - 0s 871us/sample - loss: 0.1260 - acc: 0.9432
Epoch 72/150
542/542 [==============================] - 0s 871us/sample - loss: 0.1216 - acc: 0.9470
Epoch 73/150
542/542 [==============================] - 0s 881us/sample - loss: 0.1216 - acc: 0.9467
Epoch 74/150
542/542 [==============================] - 0s 864us/sample - loss: 0.1293 - acc: 0.9415
Epoch 75/150
542/542 [==============================] - 0s 848us/sample - loss: 0.1235 - acc: 0.9460
Epoch 76/150
542/542 [==============================] - 0s 872us/sample - loss: 0.1182 - acc: 0.9465
Epoch 77/150
542/542 [==============================] - 1s 936us/sample - loss: 0.1165 - acc: 0.9485
Epoch 78/150
542/542 [==============================] - 0s 912us/sample - loss: 0.1161 - acc: 0.9487
Epoch 79/150
542/542 [==============================] - 0s 863us/sample - loss: 0.1165 - acc: 0.9488
Epoch 80/150
542/542 [==============================] - 0s 855us/sample - loss: 0.1185 - acc: 0.9489
Epoch 81/150
542/542 [==============================] - 0s 867us/sample - loss: 0.1119 - acc: 0.9528
Epoch 82/150
542/542 [==============================] - 0s 876us/sample - loss: 0.1144 - acc: 0.9502
Epoch 83/150
542/542 [==============================] - 0s 872us/sample - loss: 0.1027 - acc: 0.9550
Epoch 84/150
542/542 [==============================] - 0s 853us/sample - loss: 0.1056 - acc: 0.9544
Epoch 85/150
542/542 [==============================] - 0s 865us/sample - loss: 0.0975 - acc: 0.9572
Epoch 86/150
542/542 [==============================] - 0s 854us/sample - loss: 0.1027 - acc: 0.9563
Epoch 87/150
542/542 [==============================] - 1s 947us/sample - loss: 0.0980 - acc: 0.9581
Epoch 88/150
542/542 [==============================] - 0s 874us/sample - loss: 0.1082 - acc: 0.9518
Epoch 89/150
542/542 [==============================] - 0s 897us/sample - loss: 0.0955 - acc: 0.9575
Epoch 90/150
542/542 [==============================] - 0s 846us/sample - loss: 0.0972 - acc: 0.9584
Epoch 91/150
542/542 [==============================] - 0s 920us/sample - loss: 0.1091 - acc: 0.9560
Epoch 92/150
542/542 [==============================] - 0s 853us/sample - loss: 0.0970 - acc: 0.9586
Epoch 93/150
542/542 [==============================] - 0s 868us/sample - loss: 0.0995 - acc: 0.9569
Epoch 94/150
542/542 [==============================] - 0s 876us/sample - loss: 0.0957 - acc: 0.9582
Epoch 95/150
542/542 [==============================] - 0s 864us/sample - loss: 0.0910 - acc: 0.9589
Epoch 96/150
542/542 [==============================] - 0s 867us/sample - loss: 0.0939 - acc: 0.9590
Epoch 97/150
542/542 [==============================] - 0s 843us/sample - loss: 0.0918 - acc: 0.9607
Epoch 98/150
542/542 [==============================] - 0s 884us/sample - loss: 0.0845 - acc: 0.9628
Epoch 99/150
542/542 [==============================] - 1s 982us/sample - loss: 0.0844 - acc: 0.9632
Epoch 100/150
542/542 [==============================] - 0s 886us/sample - loss: 0.0900 - acc: 0.9614
Epoch 101/150
542/542 [==============================] - 0s 881us/sample - loss: 0.0878 - acc: 0.9627
Epoch 102/150
542/542 [==============================] - 0s 862us/sample - loss: 0.0953 - acc: 0.9593
Epoch 103/150
542/542 [==============================] - 0s 879us/sample - loss: 0.0901 - acc: 0.9621
Epoch 104/150
542/542 [==============================] - 0s 860us/sample - loss: 0.0815 - acc: 0.9646
Epoch 105/150
542/542 [==============================] - 0s 877us/sample - loss: 0.0856 - acc: 0.9624
Epoch 106/150
542/542 [==============================] - 0s 896us/sample - loss: 0.0820 - acc: 0.9637
Epoch 107/150
542/542 [==============================] - 0s 874us/sample - loss: 0.0805 - acc: 0.9656
Epoch 108/150
542/542 [==============================] - 0s 884us/sample - loss: 0.0843 - acc: 0.9642
Epoch 109/150
542/542 [==============================] - 0s 830us/sample - loss: 0.0781 - acc: 0.9662
Epoch 110/150
542/542 [==============================] - 0s 886us/sample - loss: 0.0745 - acc: 0.9692
Epoch 111/150
542/542 [==============================] - 0s 845us/sample - loss: 0.0743 - acc: 0.9698
Epoch 112/150
542/542 [==============================] - 1s 1ms/sample - loss: 0.0781 - acc: 0.9659
Epoch 113/150
542/542 [==============================] - 0s 874us/sample - loss: 0.0767 - acc: 0.9671
Epoch 114/150
542/542 [==============================] - 0s 903us/sample - loss: 0.0732 - acc: 0.9690
Epoch 115/150
542/542 [==============================] - 0s 889us/sample - loss: 0.0726 - acc: 0.9697
Epoch 116/150
542/542 [==============================] - 0s 897us/sample - loss: 0.0684 - acc: 0.9716
Epoch 117/150
542/542 [==============================] - 0s 869us/sample - loss: 0.0683 - acc: 0.9718
Epoch 118/150
542/542 [==============================] - 1s 1ms/sample - loss: 0.0771 - acc: 0.9672
Epoch 119/150
542/542 [==============================] - 0s 887us/sample - loss: 0.0721 - acc: 0.9703
Epoch 120/150
542/542 [==============================] - 0s 890us/sample - loss: 0.0704 - acc: 0.9706
Epoch 121/150
542/542 [==============================] - 0s 891us/sample - loss: 0.0697 - acc: 0.9707
Epoch 122/150
542/542 [==============================] - 0s 886us/sample - loss: 0.0742 - acc: 0.9695
Epoch 123/150
542/542 [==============================] - 0s 857us/sample - loss: 0.0708 - acc: 0.9711
Epoch 124/150
542/542 [==============================] - 0s 871us/sample - loss: 0.0724 - acc: 0.9687
Epoch 125/150
542/542 [==============================] - 0s 901us/sample - loss: 0.0708 - acc: 0.9714
Epoch 126/150
542/542 [==============================] - 0s 893us/sample - loss: 0.0695 - acc: 0.9728
Epoch 127/150
542/542 [==============================] - 0s 861us/sample - loss: 0.0685 - acc: 0.9698
Epoch 128/150
542/542 [==============================] - 0s 894us/sample - loss: 0.0639 - acc: 0.9739
Epoch 129/150
542/542 [==============================] - 0s 880us/sample - loss: 0.0594 - acc: 0.9758
Epoch 130/150
542/542 [==============================] - 0s 863us/sample - loss: 0.0595 - acc: 0.9754
Epoch 131/150
542/542 [==============================] - 0s 878us/sample - loss: 0.0586 - acc: 0.9758
Epoch 132/150
542/542 [==============================] - 0s 851us/sample - loss: 0.0640 - acc: 0.9723
Epoch 133/150
542/542 [==============================] - 0s 870us/sample - loss: 0.0627 - acc: 0.9730
Epoch 134/150
542/542 [==============================] - 0s 874us/sample - loss: 0.0580 - acc: 0.9770
Epoch 135/150
542/542 [==============================] - 0s 868us/sample - loss: 0.0577 - acc: 0.9766
Epoch 136/150
542/542 [==============================] - 0s 891us/sample - loss: 0.0615 - acc: 0.9745
Epoch 137/150
542/542 [==============================] - 1s 939us/sample - loss: 0.0653 - acc: 0.9732
Epoch 138/150
542/542 [==============================] - 0s 874us/sample - loss: 0.0573 - acc: 0.9767
Epoch 139/150
542/542 [==============================] - 0s 904us/sample - loss: 0.0612 - acc: 0.9763
Epoch 140/150
542/542 [==============================] - 0s 886us/sample - loss: 0.0564 - acc: 0.9761
Epoch 141/150
542/542 [==============================] - 0s 890us/sample - loss: 0.0559 - acc: 0.9783
Epoch 142/150
542/542 [==============================] - 0s 884us/sample - loss: 0.0602 - acc: 0.9755
Epoch 143/150
542/542 [==============================] - 0s 920us/sample - loss: 0.0584 - acc: 0.9769
Epoch 144/150
542/542 [==============================] - 0s 861us/sample - loss: 0.0523 - acc: 0.9793
Epoch 145/150
542/542 [==============================] - 0s 892us/sample - loss: 0.0581 - acc: 0.9772
Epoch 146/150
542/542 [==============================] - 0s 890us/sample - loss: 0.0638 - acc: 0.9746
Epoch 147/150
542/542 [==============================] - 0s 880us/sample - loss: 0.0562 - acc: 0.9768
Epoch 148/150
542/542 [==============================] - 0s 871us/sample - loss: 0.0603 - acc: 0.9761
Epoch 149/150
542/542 [==============================] - 0s 858us/sample - loss: 0.0549 - acc: 0.9766
Epoch 150/150
542/542 [==============================] - 0s 876us/sample - loss: 0.0488 - acc: 0.9801

# Preparing Test Data

In [19]:
# preparing test data 

# we need to have last 3 days of training data to predict the first test data

past_3_days = training_data.tail(3)

df = past_3_days.append(testing_data, ignore_index = True)

# df

## Removing Date Columns From Test Data

In [20]:
df = df.drop(["Date"],axis=1)
# df

# Normalizing Values

In [21]:
inputs  = scaler.transform(df)
inputs

array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 1., 0., ..., 0., 0., 0.],
       [1., 1., 0., ..., 1., 1., 1.],
       ...,
       [1., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 1., 0.],
       [1., 0., 0., ..., 0., 0., 1.]])

In [22]:
x_test = []
y_test = []

In [23]:
for i in range(3, inputs.shape[0]):
    x_test.append(inputs[i-3:i])
    y_test.append(inputs[i])

In [24]:
x_test, y_test = np.array(x_test), np.array(y_test)
x_test.shape, y_test.shape

((185, 3, 29), (185, 29))

# Prediction

In [25]:
# predicting item
y_pred = regressor.predict(x_test)

In [26]:
y_pred.shape

(185, 29)

In [27]:
y_pred

array([[6.0527250e-11, 5.8329321e-04, 1.9106483e-06, ..., 1.9701633e-10,
        9.7272723e-10, 3.0376107e-10],
       [9.9994957e-01, 8.5840715e-05, 2.0480077e-04, ..., 7.9009793e-10,
        2.2145143e-10, 1.4433939e-14],
       [9.9999213e-01, 1.0000000e+00, 3.0420167e-18, ..., 5.3698974e-23,
        1.3328245e-22, 4.0623955e-20],
       ...,
       [9.9476612e-01, 1.0000000e+00, 3.4815386e-08, ..., 6.0106834e-20,
        1.2466469e-18, 8.1538595e-08],
       [9.5632857e-01, 9.9707437e-01, 4.4411804e-06, ..., 9.9989927e-01,
        9.9984050e-01, 3.5167307e-08],
       [1.0000000e+00, 3.6542399e-03, 1.7267762e-07, ..., 8.7585459e-09,
        8.8987298e-09, 1.6456331e-11]], dtype=float32)

In [28]:
results = regressor.evaluate(x_test, y_test)

185/185 [==============================] - 0s 2ms/sample - loss: 0.2383 - acc: 0.9445

In [29]:
regressor.save("todoModel.h5")